extends Resource

# Key: Buildings category, Value: Building list
var tree: Dictionary[String, BuildingCategory] = self.build_default_dictionary()


func reorder_by_position() -> void:
	var categories_array = tree.keys().map(func(key): return [key, tree[key]])

	categories_array.sort_custom(func(a, b): return a[1].position < b[1].position)

	var ordered_dict: Dictionary[String, BuildingCategory] = {}
	for item in categories_array:
		ordered_dict.set(item[0], item[1])

	tree = ordered_dict


# return type: BuildingEntry|null
func search_building_by_id(buildingId : String):
	for i: String in tree:
		var buildings = tree.get(i).buildings
		var entry = buildings.get(buildingId, null)
		
		if entry is BuildingEntry:
			return entry.building
	
	return null


func merge_custom_ree(custom: Dictionary):
	custom.merge(self.tree)
	tree = custom


func build_default_dictionary() -> Dictionary[String, BuildingCategory]:
	return {
		"Production": BuildingCategory.new(
			0,
			load("res://Sprites/icon_production.png"),
			{
				"starground:building_furnace": BuildingEntry.new(
					"Furnace",
					"KEY_BUILDING_FURNACE",
					"res://Scenes/furnace.tscn",
					[
						BuildingIngredient.new("starground:stone", 10),
					],
					load("res://Sprites/furnace.png"),
					[],
					Vector2(0, -3),
					Vector2(2, 2),
					true,
					false,
				),
				"starground:building_oven": BuildingEntry.new(
					"Oven",
					"KEY_BUILDING_OVEN",
					"res://Scenes/oven.tscn",
					[
						BuildingIngredient.new("starground:stone_brick", 10),
						BuildingIngredient.new("starground:stone", 5),
					],
					load("res://Sprites/oven.png"),
					[],
					Vector2(0, -7),
					Vector2(2, 2),
					true,
					false,
				),
				"starground:building_brewing_station": BuildingEntry.new(
					"Brewing Station",
					"KEY_BUILDING_BREWING_STATION",
					"res://Scenes/brewing_station.tscn",
					[
						BuildingIngredient.new("starground:stone_brick", 5),
						BuildingIngredient.new("starground:wood", 10),
						BuildingIngredient.new("starground:iron_ingot", 10),
					],
					load("res://Sprites/brewing_station.png"),
					[],
					Vector2(0, 0),
					Vector2(3, 2),
					true,
					false,
				),
				"starground:building_electric_furnace": BuildingEntry.new(
					"Electric Furnace",
					"KEY_BUILDING_ELECTRIC_FURNACE",
					"res://Scenes/electric_furnace.tscn",
					[
						BuildingIngredient.new("starground:plastic", 10),
						BuildingIngredient.new("starground:steel", 10),
						BuildingIngredient.new("starground:copper_ingot", 5),
					],
					load("res://Sprites/electric_furnace.png"),
					[],
					Vector2(0, 0),
					Vector2(3, 3),
					false,
					false,
					-10,
				),
				"starground:building_crafter": BuildingEntry.new(
					"Crafter",
					"KEY_BUILDING_CRAFTER",
					"res://Scenes/crafter.tscn",
					[
						BuildingIngredient.new("starground:iron_ingot", 5),
						BuildingIngredient.new("starground:copper_ingot", 5),
					],
					load("res://Sprites/crafter.png"),
					[],
					Vector2(0, -3),
					Vector2(2, 2),
					false,
					false,
					-5,
				),
				"starground:building_purifier": BuildingEntry.new(
					"Purifier",
					"KEY_BUILDING_PURIFIER",
					"res://Scenes/purifier.tscn",
					[
						BuildingIngredient.new("starground:cobalt_ingot", 5),
						BuildingIngredient.new("starground:steel", 5),
						BuildingIngredient.new("starground:stone_brick", 5),
					],
					load("res://Sprites/purifier.png"),
					[],
					Vector2(0, 0),
					Vector2(3, 3),
					false,
					false,
					-8,
				),
				"starground:building_collector": BuildingEntry.new(
					"Collector",
					"KEY_BUILDING_COLLECTOR",
					"res://Scenes/collector.tscn",
					[
						BuildingIngredient.new("starground:copper_ingot", 10),
						BuildingIngredient.new("starground:gear", 5),
					],
					load("res://Sprites/collector.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
					false,
					false,
					-5,
				),
				"starground:building_oil_rig": BuildingEntry.new(
					"Oil Rig",
					"KEY_BUILDING_OIL_RIG",
					"res://Scenes/oil_rig.tscn",
					[
						BuildingIngredient.new("starground:rotor", 5),
						BuildingIngredient.new("starground:processor", 2),
					],
					load("res://Sprites/oil_rig.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
					false,
					true,
					-5,
					false,
					false,
					true,
				),
				"starground:building_harvester": BuildingEntry.new(
					"Harvester",
					"KEY_BUILDING_HARVESTER",
					"res://Scenes/harvester.tscn",
					[
						BuildingIngredient.new("starground:plastic", 5),
						BuildingIngredient.new("starground:copper_ingot", 10),
					],
					load("res://Sprites/harvester.png"),
					[],
					Vector2(0, 0),
					Vector2(3, 3),
					false,
					true,
					-5,
				),
				"starground:building_researcher": BuildingEntry.new(
					"Researcher",
					"KEY_BUILDING_RESEARCHER",
					"res://Scenes/researcher.tscn",
					[
						BuildingIngredient.new("starground:iron_ingot", 10),
						BuildingIngredient.new("starground:processor", 5),
					],
					load("res://Sprites/researcher.png"),
					[],
					Vector2(0, 0),
					Vector2(3, 3),
					false,
					true,
					-8,
					false,
					true,
					false,
					false,
				),
				"starground:building_foundry": BuildingEntry.new(
					"Foundry",
					"KEY_BUILDING_FOUNDRY",
					"res://Scenes/foundry.tscn",
					[
						BuildingIngredient.new("starground:stone_brick", 20),
						BuildingIngredient.new("starground:iron_ingot", 10),
					],
					load("res://Sprites/foundry.png"),
					[],
					Vector2(0, 0),
					Vector2(3, 3),
					true,
					false,
				),
				"starground:building_refiner": BuildingEntry.new(
					"Refiner",
					"KEY_BUILDING_REFINER",
					"res://Scenes/refiner.tscn",
					[
						BuildingIngredient.new("starground:rotor", 5),
						BuildingIngredient.new("starground:copper_ingot", 5),
						BuildingIngredient.new("starground:processor", 2),
					],
					load("res://Sprites/refiner.png"),
					[],
					Vector2(0, -8),
					Vector2(3, 2),
					false,
					false,
					-5,
				),
				"starground:building_thumper": BuildingEntry.new(
					"Thumper",
					"KEY_BUILDING_THUMPER",
					"res://Scenes/thumper.tscn",
					[
						BuildingIngredient.new("starground:plastic", 20),
						BuildingIngredient.new("starground:steel", 20),
						BuildingIngredient.new("starground:rotor", 10),
					],
					load("res://Sprites/thumper.png"),
					[],
					Vector2(0, 0),
					Vector2(5, 5),
					false,
					true,
					-30,
				),
				"starground:building_water_pump": BuildingEntry.new(
					"Water Pump",
					"KEY_BUILDING_WATER_PUMP",
					"res://Scenes/water_pump.tscn",
					[
						BuildingIngredient.new("starground:iron_ingot", 2),
						BuildingIngredient.new("starground:copper_ingot", 5),
					],
					load("res://Sprites/water_pump.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
					false,
					true,
					0,
					false,
					false,
					true,
				),
				"starground:building_farm_plot": BuildingEntry.new(
					"Farm Plot",
					"KEY_BUILDING_FARM_PLOT",
					"res://Scenes/farm_plot.tscn",
					[
						BuildingIngredient.new("starground:wood", 5),
					],
					load("res://Sprites/farm_plot.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
				),
				"starground:building_grinder": BuildingEntry.new(
					"Grinder",
					"KEY_BUILDING_GRINDER",
					"res://Scenes/grinder.tscn",
					[
						BuildingIngredient.new("starground:stone_brick", 10),
						BuildingIngredient.new("starground:gear", 3),
						BuildingIngredient.new("starground:copper_wire", 4),
					],
					load("res://Sprites/grinder.png"),
					[],
					Vector2(0, 0),
					Vector2(3, 2),
					false,
					false,
					-10,
				),
			}
		),
		"Logistics": BuildingCategory.new(
			10,
			load("res://Sprites/icon_production.png"),
			{
				"starground:building_mover": BuildingEntry.new(
					"Mover",
					"KEY_BUILDING_MOVER",
					"res://Scenes/mover.tscn",
					[
						BuildingIngredient.new("starground:iron_ingot", 3),
					],
					load("res://Sprites/mover_preview_down.png"),
					[
						load("res://Sprites/mover_preview_down.png"),
						load("res://Sprites/mover_preview_left.png"),
						load("res://Sprites/mover_preview_up.png"),
						load("res://Sprites/mover_preview_right.png"),
					],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					true,
					0,
					true
				),
				"starground:building_long_range_mover": BuildingEntry.new(
					"Long Range Mover",
					"KEY_BUILDING_LONG_RANGE_MOVER",
					"res://Scenes/mover_long.tscn",
					[
						BuildingIngredient.new("starground:iron_ingot", 3),
						BuildingIngredient.new("starground:copper_wire", 2),
					],
					load("res://Sprites/mover_long_preview_down.png"),
					[
						load("res://Sprites/mover_long_preview_down.png"),
						load("res://Sprites/mover_long_preview_left.png"),
						load("res://Sprites/mover_long_preview_up.png"),
						load("res://Sprites/mover_long_preview_right.png"),
					],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					true,
					0,
					true,
					true,
				),
				"starground:building_conveyor": BuildingEntry.new(
					"Conveyor",
					"KEY_BUILDING_CONVEYOR",
					"res://Scenes/conveyor.tscn",
					[
						BuildingIngredient.new("starground:iron_ingot", 1),
					],
					load("res://Sprites/conveyor.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					true,
					0,
					true,
					false,
				),
				"starground:building_underground_conveyor": BuildingEntry.new(
					"Underground Conveyor",
					"KEY_BUILDING_UNDERGROUND_CONVEYOR",
					"res://Scenes/underground_conveyor.tscn",
					[
						BuildingIngredient.new("starground:iron_ingot", 5),
						BuildingIngredient.new("starground:stone_brick", 5),
					],
					load("res://Sprites/underground_conveyor_entrance_preview_(0, 1).png"),
					[
						load("res://Sprites/underground_conveyor_entrance_preview_(0, 1).png"),
						load("res://Sprites/underground_conveyor_entrance_preview_(-1, 0).png"),
						load("res://Sprites/underground_conveyor_entrance_preview_(0, -1).png"),
						load("res://Sprites/underground_conveyor_entrance_preview_(1, 0).png"),
					],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					true,
					0,
					true,
					false
				),
				"starground:building_underground_conveyor_v2": BuildingEntry.new(
					"Underground Conveyor V2",
					"KEY_BUILDING_UNDERGROUND_CONVEYOR_V2",
					"res://Scenes/underground_conveyor_v2.tscn",
					[
						BuildingIngredient.new("starground:processor", 5),
						BuildingIngredient.new("starground:stone_brick", 10),
					],
					load("res://Sprites/underground_conveyor_v2_entrance_preview_(0, 1).png"),
					[
						load("res://Sprites/underground_conveyor_v2_entrance_preview_(0, 1).png"),
						load("res://Sprites/underground_conveyor_v2_entrance_preview_(-1, 0).png"),
						load("res://Sprites/underground_conveyor_v2_entrance_preview_(0, -1).png"),
						load("res://Sprites/underground_conveyor_v2_entrance_preview_(1, 0).png"),
					],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					true,
					0,
					true,
					false,
				),
				"starground:building_conveyor_v2": BuildingEntry.new(
					"Conveyor V2",
					"KEY_BUILDING_CONVEYOR_V2",
					"res://Scenes/conveyor_v2.tscn",
					[
						BuildingIngredient.new("starground:copper_ingot", 1),
						BuildingIngredient.new("starground:gear", 1),
					],
					load("res://Sprites/conveyor_v2.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					true,
					0,
					true,
					false,
				),
				"starground:building_chest": BuildingEntry.new(
					"Chest",
					"KEY_BUILDING_CHEST",
					"res://Scenes/chest.tscn",
					[
						BuildingIngredient.new("starground:stone", 5),
						BuildingIngredient.new("starground:wood", 5),
					],
					load("res://Sprites/chest.png"),
				),
				"starground:building_storage_hub": BuildingEntry.new(
					"Storage Hub",
					"KEY_BUILDING_STORAGE_HUB",
					"res://Scenes/storage_hub.tscn",
					[
						BuildingIngredient.new("starground:stone_brick", 20),
						BuildingIngredient.new("starground:copper_ingot", 20),
					],
					load("res://Sprites/storage_hub.png"),
					[],
					Vector2(0, 0),
					Vector2(3, 3),
				),
				"starground:building_big_chest": BuildingEntry.new(
					"Big Chest",
					"KEY_BUILDING_BIG_CHEST",
					"res://Scenes/big_chest.tscn",
					[
						BuildingIngredient.new("starground:stone_brick", 10),
						BuildingIngredient.new("starground:wood", 10),
					],
					load("res://Sprites/big_chest.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 1),
				),
				"starground:building_splitter": BuildingEntry.new(
					"Splitter",
					"KEY_BUILDING_SPLITTER",
					"res://Scenes/splitter.tscn",
					[
						BuildingIngredient.new("starground:copper_wire", 4),
						BuildingIngredient.new("starground:gear", 1),
					],
					load("res://Sprites/splitter_preview_down.png"),
					[
						load("res://Sprites/splitter_preview_down.png"),
						load("res://Sprites/splitter_preview_left.png"),
						load("res://Sprites/splitter_preview_up.png"),
						load("res://Sprites/splitter_preview_right.png"),
					],
					Vector2(0, 0),
					Vector2(2, 1),
					false,
					true,
					0,
					true,
					false
				),
				"starground:building_splitter_v2": BuildingEntry.new(
					"Splitter V2",
					"KEY_BUILDING_SPLITTER",
					"res://Scenes/splitter_v2.tscn",
					[
						BuildingIngredient.new("starground:processor", 5),
						BuildingIngredient.new("starground:gear", 2),
					],
					load("res://Sprites/splitter_v2_preview_down.png"),
					[
						load("res://Sprites/splitter_v2_preview_down.png"),
						load("res://Sprites/splitter_v2_preview_left.png"),
						load("res://Sprites/splitter_v2_preview_up.png"),
						load("res://Sprites/splitter_v2_preview_right.png"),
					],
					Vector2(0, 0),
					Vector2(2, 1),
					false,
					true,
					0,
					true,
					false
				),
				"starground:building_shredder": BuildingEntry.new(
					"Shredder",
					"KEY_BUILDING_SHREDDER",
					"res://Scenes/shredder.tscn",
					[
						BuildingIngredient.new("starground:stone_brick", 5),
						BuildingIngredient.new("starground:gear", 3),
						BuildingIngredient.new("starground:copper_wire", 2),
					],
					load("res://Sprites/shredder.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
					false,
					false,
					-3,
				),
				"starground:building_space_elevator": BuildingEntry.new(
					"Space Elevator",
					"KEY_BUILDING_SPACE_ELEVATOR",
					"res://Scenes/space_elevator.tscn",
					[
						BuildingIngredient.new("starground:cobalt_ingot", 30),
						BuildingIngredient.new("starground:depleted_uranium", 15),
						BuildingIngredient.new("starground:rotor", 10),
						BuildingIngredient.new("starground:processor", 10),
						BuildingIngredient.new("starground:steel", 10),
					],
					load("res://Sprites/space_elevator.png"),
					[],
					Vector2(0, -96),
					Vector2(6, 6),
					false,
					true,
					-40
				),
				"starground:building_vault": BuildingEntry.new(
					"Vault",
					"KEY_BUILDING_VAULT",
					"res://Scenes/vault.tscn",
					[
						BuildingIngredient.new("starground:steel", 10),
						BuildingIngredient.new("starground:stone_brick", 10),
					],
					load("res://Sprites/vault.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
				)
			}
		),
		"Power" : BuildingCategory.new(
			20,
			load("res://Sprites/icon_production.png"),
			{
				"starground:building_nuclear_reactor": BuildingEntry.new(
				"Nuclear Reactor",
				"KEY_BUILDING_NUCLEAR_REACTOR",
				"res://Scenes/nuclear_reactor.tscn",
					[
					BuildingIngredient.new("starground:cobalt_ingot", 20),
					BuildingIngredient.new("starground:copper_wire", 5),
					BuildingIngredient.new("starground:stone_brick", 20),
				],
				load("res://Sprites/nuclear_reactor.png"),
				[],
				Vector2(0, -5),
				Vector2(4, 4),
				false,
				false,
				),
				"starground:building_nuclear_turbine": BuildingEntry.new(
					"Nuclear Turbine",
					"KEY_BUILDING_NUCLEAR_TURBINE",
					"res://Scenes/nuclear_turbine.tscn",
					[
						BuildingIngredient.new("starground:stone_brick", 20),
						BuildingIngredient.new("starground:rotor", 5),
					],
					load("res://Sprites/nuclear_turbine.png"),
					[],
					Vector2(0, -3),
					Vector2(4, 4),
					true,
					false,
					40,
				),
				"starground:building_treadmill": BuildingEntry.new(
					"Treadmill",
					"KEY_BUILDING_TREADMILL",
					"res://Scenes/treadmill.tscn",
					[
						BuildingIngredient.new("starground:iron_ingot", 5),
					],
					load("res://Sprites/treadmill.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
					false,
					false,
					20,
				),
				"starground:building_burner": BuildingEntry.new(
					"Burner",
					"KEY_BUILDING_BURNER",
					"res://Scenes/burner.tscn",
					[
						BuildingIngredient.new("starground:stone_brick", 10),
						BuildingIngredient.new("starground:copper_ingot", 2),
					],
					load("res://Sprites/burner.png"),
					[],
					Vector2(0, -5),
					Vector2(2, 2),
					true,
					false,
					20,
				),
				"starground:building_tesla_coil": BuildingEntry.new(
					"Tesla Coil",
					"KEY_BUILDING_TESLA_COIL",
					"res://Scenes/tesla_coil.tscn",
					[
						BuildingIngredient.new("starground:copper_ingot", 1),
						BuildingIngredient.new("starground:stone", 1),
					],
					load("res://Sprites/tesla_coil.png"),
					[],
					Vector2(0, -8),
					Vector2(1, 1),
					false,
					false,
				),
				"starground:building_tesla_coil_v2": BuildingEntry.new(
					"Tesla Coil V2",
					"KEY_BUILDING_TESLA_COIL",
					"res://Scenes/tesla_coil_v2.tscn",
					[
						BuildingIngredient.new("starground:copper_ingot", 2),
						BuildingIngredient.new("starground:cobalt_ingot", 2),
					],
					load("res://Sprites/tesla_coil_v2.png"),
					[],
					Vector2(0, -8),
					Vector2(1, 1),
					false,
					true,
					0,
					false,
					true,
					true,
				),
				"starground:building_solar_panel": BuildingEntry.new(
					"Solar Panel",
					"KEY_BUILDING_SOLAR_PANEL",
					"res://Scenes/solar_panel.tscn",
					[
						BuildingIngredient.new("starground:steel", 5),
						BuildingIngredient.new("starground:processor", 5),
						BuildingIngredient.new("starground:stone_brick", 5),
					],
					load("res://Sprites/solar_panel.png"),
					[],
					Vector2(0, 0),
					Vector2(3, 3),
					false,
					false,
					10,
					false,
					false,
				),
				"starground:building_battery": BuildingEntry.new(
					"Battery",
					"KEY_BUILDING_BATTERY",
					"res://Scenes/battery.tscn",
					[
						BuildingIngredient.new("starground:copper_ingot", 10),
					],
					load("res://Sprites/battery.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					false,
				),
				"starground:building_big_battery": BuildingEntry.new(
					"Big Battery",
					"KEY_BUILDING_BIG_BATTERY",
					"res://Scenes/big_battery.tscn",
					[
						BuildingIngredient.new("starground:copper_wire", 10),
						BuildingIngredient.new("starground:steel", 5),
					],
					load("res://Sprites/big_battery.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
					false,
					false,
				),
			}
		),
		"Decorations": BuildingCategory.new(
			30,
			load("res://Sprites/icon_production.png"),
			{
				"starground:building_fence": BuildingEntry.new(
					"Fence",
					"KEY_BUILDING_FENCE",
					"res://Scenes/fence.tscn",
					[
						BuildingIngredient.new("starground:wood", 2),
					],
					load("res://Sprites/fence_icon.png"),
				),
				"starground:building_fence_gate": BuildingEntry.new(
					"Fence Gate",
					"KEY_BUILDING_FENCE",
					"res://Scenes/fence_gate.tscn",
					[
						BuildingIngredient.new("starground:wood", 2),
						BuildingIngredient.new("starground:stone", 2),
					],
					load("res://Sprites/fence_gate_icon.png"),
				),
				"starground:building_plant_1": BuildingEntry.new(
					"Plant 1",
					"KEY_BUILDING_PLANT",
					"res://Scenes/plant_1.tscn",
					[
						BuildingIngredient.new("starground:wood", 5),
						BuildingIngredient.new("starground:stone_brick", 2),
					],
					load("res://Sprites/plant_1.png"),
					[],
					Vector2(0, -8),
					Vector2(1, 1),
				),
				"starground:building_plant_2": BuildingEntry.new(
					"Plant 2",
					"KEY_BUILDING_PLANT",
					"res://Scenes/plant_2.tscn",
					[
						BuildingIngredient.new("starground:wood", 5),
						BuildingIngredient.new("starground:stone_brick", 2),
					],
					load("res://Sprites/plant_2.png"),
					[],
					Vector2(0, -8),
					Vector2(1, 1),
				),
				"starground:building_plant_3": BuildingEntry.new(
					"Plant 3",
					"KEY_BUILDING_PLANT",
					"res://Scenes/plant_3.tscn",
					[
					BuildingIngredient.new("starground:wood", 5),
					BuildingIngredient.new("starground:stone_brick", 2),
					],
					load("res://Sprites/plant_3.png"),
					[],
					Vector2(0, -8),
					Vector2(1, 1),
				),
				"starground:building_christmas_tree": BuildingEntry.new(
					"Christmas Tree",
					"KEY_BUILDING_CHRISTMAS_TREE",
					"res://Scenes/christmas_tree.tscn",
					[
						BuildingIngredient.new("starground:wood", 10),
						BuildingIngredient.new("starground:plastic", 5),
						BuildingIngredient.new("starground:copper_wire", 2),
					],
					load("res://Sprites/christmas_tree.png"),
					[],
					Vector2(0, -12),
					Vector2(2, 2),
				),
				"starground:building_present": BuildingEntry.new(
					"Present",
					"KEY_BUILDING_CHRISTMAS_TREE",
					"res://Scenes/present.tscn",
					[
						BuildingIngredient.new("starground:wood", 5),
						BuildingIngredient.new("starground:plastic", 5),
					],
					load("res://Sprites/present.png"),
					[],
					Vector2(0, -1),
					Vector2(1, 1),
				),
				"starground:building_snowman": BuildingEntry.new(
					"Snowman",
					"KEY_BUILDING_CHRISTMAS_TREE",
					"res://Scenes/snowman.tscn",
					[
						BuildingIngredient.new("starground:water", 20)
					],
					load("res://Sprites/snowman.png"),
					[],
					Vector2(0, -4),
					Vector2(1, 1),
				),
				"starground:building_dreadcap_monument": BuildingEntry.new(
					"Dreadcap Monument",
					"KEY_BUILDING_DREADCAP_MONUMENT",
					"res://Scenes/dreadcap_monument.tscn",
					[
						BuildingIngredient.new("starground:dreadcap_trophy", 1),
					],
					load("res://Sprites/dreadcap_monument.png"),
					[],
					Vector2(0, -6.5),
					Vector2(2, 2),
				),
				"starground:building_spore_monument": BuildingEntry.new(
					"Spore Monument",
					"KEY_BUILDING_SPORE_MONUMENT",
					"res://Scenes/spore_monument.tscn",
					[
						BuildingIngredient.new("starground:spore_trophy", 1)
					],
					load("res://Sprites/spore_monument.png"),
					[],
					Vector2(0, -6.5),
					Vector2(2, 2),
				),
				"starground:building_godot_plush": BuildingEntry.new(
					"Godot Plush",
					"KEY_BUILDING_GODOT_PLUSH",
					"res://Scenes/godot_plush.tscn",
					[
						BuildingIngredient.new("starground:plastic", 5),
					],
					load("res://Sprites/godot_plush.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
				),
				"starground:building_stone_wall": BuildingEntry.new(
					"Stone Wall",
					"KEY_BUILDING_STONE_WALL",
					"res://Scenes/stone_wall.tscn",
					[
						BuildingIngredient.new("starground:stone", 1),
					],
					load("res://Sprites/stone_wall_side.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 1),
				),
				"starground:building_lamp": BuildingEntry.new(
					"Lamp",
					"KEY_BUILDING_LAMP",
					"res://Scenes/lamp.tscn",
					[
						BuildingIngredient.new("starground:copper_ingot", 2),
						BuildingIngredient.new("starground:copper_wire", 2),
					],
					load("res://Sprites/lamp.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					false,
					-1,
					false,
					false,
				),
				"starground:building_beach_ball": BuildingEntry.new(
					"Beach Ball",
					"KEY_BUILDING_BEACH_BALL",
					"res://Scenes/pongball.tscn",
					[
						BuildingIngredient.new("starground:plastic", 5),
					],
					load("res://Sprites/beachball.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
					false,
					false,
					0,
					false,
					false,
				),
				"starground:building_rubber_ducky": BuildingEntry.new(
					"Rubber Ducky",
					"KEY_BUILDING_RUBBER_DUCKY",
					"res://Scenes/rubber_ducky.tscn",
					[
						BuildingIngredient.new("starground:plastic", 5)
					],
					load("res://Sprites/rubber_ducky.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					true,
					0,
					false,
					false,
					true,
					true,
				),
			}
		),
		"Miscellaneous" : BuildingCategory.new(
			40,
			load("res://Sprites/icon_production.png"),
			{
				"starground:building_trough": BuildingEntry.new(
					"Trough",
					"KEY_BUILDING_TROUGH",
					"res://Scenes/trough.tscn",
					[
						BuildingIngredient.new("starground:stone_brick", 5),
						BuildingIngredient.new("starground:iron_ingot", 5),
					],
					load("res://Sprites/trough_icon.png"),
					[],
					Vector2(0, 0),
					Vector2(4, 2),
				),
				"starground:building_pressure_pump": BuildingEntry.new(
					"Pressure Pump",
					"KEY_BUILDING_PRESSURE_PUMP",
					"res://Scenes/pressure_pump.tscn",
					[
						BuildingIngredient.new("starground:cobalt_ingot", 5),
						BuildingIngredient.new("starground:plastic", 5),
						BuildingIngredient.new("starground:rotor", 5),
					],
					load("res://Sprites/pressure_pump.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
				),
				"starground:building_pressure_wall": BuildingEntry.new(
					"Pressure Wall",
					"KEY_BUILDING_PRESSURE_WALL",
					"res://Scenes/pressure_wall.tscn",
					[
						BuildingIngredient.new("starground:cobalt_ingot", 2),
					],
					load("res://Sprites/pressure_wall_side.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 3),
				),
				"starground:building_pressure_airlock": BuildingEntry.new(
					"Pressure Airlock",
					"KEY_BUILDING_PRESSURE_AIRLOCK",
					"res://Scenes/pressure_airlock.tscn",
					[
						BuildingIngredient.new("starground:cobalt_ingot", 5),
						BuildingIngredient.new("starground:plastic", 5),
					],
					load("res://Sprites/pressure_airlock.png"),
					[
						load("res://Sprites/pressure_airlock.png"),
						load("res://Sprites/pressure_airlock_side.png"),
						load("res://Sprites/pressure_airlock.png"),
						load("res://Sprites/pressure_airlock_side.png")
					],
					Vector2(0, 0),
					Vector2(3, 3),
					false,
					true,
					0,
					true,
				),
				"starground:building_pressure_storage_interface": BuildingEntry.new(
					"Pressure Storage Interface",
					"KEY_BUILDING_PRESSURE_STORAGE_INTERFACE",
					"res://Scenes/pressure_storage_interface.tscn",
					[
						BuildingIngredient.new("starground:cobalt_ingot", 5),
					],
						load("res://Sprites/pressure_storage_interface.png"),
					[
						load("res://Sprites/pressure_storage_interface.png"),
						load("res://Sprites/pressure_storage_interface_side.png"),
						load("res://Sprites/pressure_storage_interface.png"),
						load("res://Sprites/pressure_storage_interface_side.png"),
					],
					Vector2(0, 0),
					Vector2(3, 3),
					false,
					true,
					0,
					true,
				),
				"starground:building_computer": BuildingEntry.new(
					"Computer",
					"KEY_BUILDING_COMPUTER",
					"res://Scenes/computer.tscn",
					[
						BuildingIngredient.new("starground:processor", 4),
						BuildingIngredient.new("starground:copper_wire", 4),
					],
					load("res://Sprites/computer.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
					false,
					false,
					-5,
					false,
					true,
					false,
					false,
					false,
				),
				"starground:building_boat": BuildingEntry.new(
					"Boat",
					"KEY_BUILDING_BOAT",
					"res://Scenes/boat.tscn",
					[
						BuildingIngredient.new("starground:wood", 10),
					],
					load("res://Sprites/boat.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
					false,
					true,
					0,
					false,
					false,
					true,
				),
				"starground:building_skateboard": BuildingEntry.new(
					"Skateboard",
					"KEY_BUILDING_SKATEBOARD",
					"res://Scenes/skateboard.tscn",
					[
						BuildingIngredient.new("starground:wood", 10),
						BuildingIngredient.new("starground:steel", 10),
						BuildingIngredient.new("starground:plastic", 5),
					],
					load("res://Sprites/skateboard.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 1),
				),
				"starground:building_land_tile": BuildingEntry.new(
					"Land Tile",
					"KEY_BUILDING_LAND_TILE",
					"res://Scenes/land_tile.tscn",
					[
						BuildingIngredient.new("starground:land_tile", 1)
					],
					load("res://Sprites/land_tile_building.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					true,
					0,
					false,
					false,
					true,
					true,
					false,
					Vector2(0, 0),
					["starground:region_tyria"],
				),
				"starground:building_training_dummy": BuildingEntry.new(
					"Training Dummy",
					"KEY_BUILDING_TRAINING_DUMMY",
					"res://Scenes/training_dummy.tscn",
					[
						BuildingIngredient.new("starground:wood", 10),
					],
					load("res://Sprites/training_dummy_full.png"),
					[],
					Vector2(0, -6.5),
					Vector2(1, 1),
				),
				"starground:building_starlauncher": BuildingEntry.new(
					"Starlauncher",
					"KEY_BUILDING_STARLAUNCHER",
					"res://Scenes/spaceship.tscn",
					[
						BuildingIngredient.new("starground:iron_ingot", 20),
						BuildingIngredient.new("starground:stone_brick", 20),
					],
					load("res://Sprites/starlauncher_preview.png"),
					[],
					Vector2(0, -8),
					Vector2(3, 3),
				),
				"starground:building_speaker": BuildingEntry.new(
					"Speaker",
					"KEY_BUILDING_SPEAKER",
					"res://Scenes/speaker.tscn",
					[
						BuildingIngredient.new("starground:wood", 10),
						BuildingIngredient.new("starground:iron_ingot", 5),
					],
					load("res://Sprites/speaker.png"),
					[],
					Vector2(0, 0),
					Vector2(1, 1),
					false,
					false,
				),
				"starground:building_tool_bench": BuildingEntry.new(
					"Tool Bench",
					"KEY_BUILDING_TOOL_BENCH",
					"res://Scenes/tool_bench.tscn",
					[
						BuildingIngredient.new("starground:iron_ingot", 2),
						BuildingIngredient.new("starground:wood", 5),
						BuildingIngredient.new("starground:stone_brick", 5),
					],
					load("res://Sprites/tool_bench.png"),
					[],
					Vector2(0, 0),
					Vector2(2, 2),
				),
			}
		),
	}
